"use strict";
(() => {
 const $=id=>document.getElementById(id),auth=window.PEACSession;
 const names={home:'Your PEAC home.',overview:'The kindness overview.',reports:'Your impact, in perspective.',people:'Log compliments.',lunch:'A place at the table.',website:'Your public welcome.',assistant:'Ask PEAC Assistant.',feedback:'Help improve PEAC.',soon:'More good things ahead.',settings:'A trustworthy workspace.'};
 let section='home',queue=null,selected=null,editingContact=null,config=null,mailEnabled=false,assistantHistory=[];
 const busy=new Set();
 const node=(tag,cls='',text='')=>{const n=document.createElement(tag);n.className=cls;n.textContent=text;return n;};
 function say(id,message,bad=false){const n=$(id);if(n){n.textContent=message;n.classList.toggle('error',bad);}}
 async function work(button,status,fn){if(busy.has(button))return;busy.add(button);const b=$(button);if(b)b.disabled=true;try{await fn();}catch(e){say(status,e.name==='AbortError'?'Response timed out. Keep the same details and retry before creating another save.':e.message,true);}finally{busy.delete(button);if(b)b.disabled=false;}}
 function syncNav(name){section=name;document.querySelectorAll('[data-portal-panel]').forEach(n=>n.classList.toggle('hidden',n.dataset.portalPanel!==name));document.querySelectorAll('.console-nav [data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===name));$('consoleTitle').textContent=names[name]||names.overview;}
 function navigate(name){if(!names[name])name='home';if(name==='website'&&auth.state.user?.role!=='admin')name='home';syncNav(name);if(name==='overview'||name==='reports')window.PEACWorkspace.showReports(name==='reports');else{$('dashboardView').classList.add('hidden');$('reportsSection').classList.add('hidden');const target=document.querySelector(`[data-portal-panel="${name}"]`);target.focus();}
   history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'auto'});
   if(name==='home')loadHome().catch(e=>say('dataStatus',e.message,true));
   if(name==='people')loadPeople().catch(e=>say('peopleStatus',e.message,true));
   if(name==='lunch')loadLunch().catch(e=>say('lunchQueueStatus',e.message,true));
   if(name==='website')loadWebsite().catch(e=>say('websiteStatus',e.message,true));
   if(name==='assistant'){loadAssistantFaqs().catch(e=>say('chatStatus',e.message,true));if(auth.state.user?.role==='admin'){loadKnowledge().catch(e=>say('faqStatus',e.message,true));loadUsage().catch(e=>say('faqStatus',e.message,true));}}
   if(name==='settings'&&auth.state.user?.role==='admin')loadUsers().catch(e=>say('userStatus',e.message,true));
 }
 window.addEventListener('peac:view',e=>syncNav(e.detail));
 document.addEventListener('click',e=>{const a=e.target.closest('[data-nav]');if(a){e.preventDefault();navigate(a.dataset.nav);}});
 window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
 $('logoutButton').addEventListener('click',()=>work('logoutButton','dataStatus',async()=>{await auth.api('/api/auth/logout','POST',{});sessionStorage.removeItem('peac.pending');location.replace('/login');}));
 const mobileLogout=node('button','outline-btn','Sign out');mobileLogout.id='topLogoutButton';mobileLogout.type='button';mobileLogout.addEventListener('click',()=>$('logoutButton').click());document.querySelector('.topbar .actions').append(mobileLogout);
 function recipientPicker(target,contacts,selectedIds=[]){const wrap=$(target);wrap.replaceChildren();const active=contacts.filter(c=>c.active);if(!active.length){wrap.append(node('p','muted','No approved contacts yet. An administrator can add them in Public website.'));return;}for(const c of active){const label=node('label','recipient-option'),input=node('input');input.type='checkbox';input.value=c.id;input.checked=selectedIds.includes(c.id);const info=node('span');info.append(node('strong','',c.label),node('small','',c.email));label.append(input,info);wrap.append(label);}}
 const selectedContacts=target=>Array.from($(target).querySelectorAll('input:checked'),n=>n.value);
 async function loadPeople(){const data=await auth.api('/api/portal/compliment-people');window.__peacPeople=data;$('peopleRows').textContent=data.total_records.toLocaleString();$('peopleCompliments').textContent=data.total_compliments.toLocaleString();$('peopleStudents').textContent=data.distinct_names.toLocaleString();renderPeople();renderRoster();say('peopleStatus',data.truncated?'Showing the latest 5,000 rows. Use the private export for older records.':'');}
 function renderPeople(){const data=window.__peacPeople;if(!data)return;const q=$('peopleSearch').value.trim().toLowerCase(),g=$('peopleGradeFilter').value,wrap=$('peopleTable');wrap.replaceChildren();const rows=data.records.filter(r=>(g==='all'||r.grade===g)&&(`${r.name} ${r.week_start}`).toLowerCase().includes(q));if(!rows.length){const tr=node('tr'),td=node('td','muted','No saved rows match this view.');td.colSpan=5;tr.append(td);wrap.append(tr);return;}for(const r of rows){const tr=node('tr');tr.append(node('td','',r.week_start),node('td','',r.name),node('td','',r.grade==='unassigned'?'—':r.grade),node('td','',String(r.count)));const td=node('td'),b=node('button','text-btn','Delete');b.type='button';b.addEventListener('click',()=>{if(!confirm(`Delete ${r.name}'s ${r.week_start} weekly row? This also removes those counts from the dashboard.`))return;work('reloadPeople','peopleStatus',async()=>{await auth.mutate('person-delete:'+r.id,'/api/portal/compliment-people/'+r.id,'DELETE',{confirm:'DELETE NAMED COMPLIMENT ROW'});await loadPeople();window.PEACWorkspace.refresh?.();say('peopleStatus','Row deleted and dashboard totals updated.');});});td.append(b);tr.append(td);wrap.append(tr);}}
 function mondayValue(){const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
 function entryMode(mode){document.querySelectorAll('[data-entry-mode]').forEach(b=>{const on=b.dataset.entryMode===mode;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});document.querySelectorAll('[data-entry-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.entryPanel!==mode));if(mode==='roster')renderRoster();}
 document.querySelectorAll('[data-entry-mode]').forEach(b=>b.addEventListener('click',()=>entryMode(b.dataset.entryMode)));
 $('personWeek').value=$('rapidWeek').value=$('rosterWeek').value=mondayValue();
 $('personLogForm').addEventListener('submit',e=>{e.preventDefault();work('savePersonLog','personLogStatus',async()=>{const existing=window.__peacPeople?.records.find(r=>r.week_start===$('personWeek').value&&r.grade===$('personGrade').value&&r.name.trim().toLocaleLowerCase()===$('personName').value.trim().toLocaleLowerCase());const payload={week_start:$('personWeek').value,name:$('personName').value,grade:$('personGrade').value,count:Number($('personCount').value),trash_count:existing?.trash_count||0,note:$('personNote').value};const r=await auth.mutate('person-log','/api/portal/compliment-people','POST',payload);$('personName').value='';$('personCount').value='0';$('personNote').value='';await loadPeople();window.PEACWorkspace.refresh?.();say('personLogStatus',r.updated?'Existing weekly total corrected.':'Weekly total saved.');});});
 let rapidRecords=[];
 function parseRapid(){const week=$('rapidWeek').value,defaultGrade=$('rapidGrade').value,lines=$('rapidText').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!week)throw new Error('Choose the week first.');if(!lines.length)throw new Error('Enter at least one name.');if(lines.length>5000)throw new Error('Rapid List supports up to 5,000 lines at a time.');const map=new Map();for(let i=0;i<lines.length;i++){const raw=lines[i];let parts=raw.split(/\s*[|,\t]\s*/).filter(Boolean);let name='',grade=defaultGrade,count=1;if(parts.length===1){name=parts[0];}else if(parts.length===2&&/^\d+$/.test(parts[1])){name=parts[0];count=Number(parts[1]);}else if(parts.length===3&&/^(6|7|8|unassigned)$/i.test(parts[1])&&/^\d+$/.test(parts[2])){name=parts[0];grade=parts[1].toLowerCase();count=Number(parts[2]);}else throw new Error(`Line ${i+1} is not understood: “${raw}”. Use Name, Name | total, or Name | grade | total.`);name=name.trim().replace(/\s+/g,' ');if(!name)throw new Error(`Line ${i+1} needs a name.`);if(name.length>120)throw new Error(`Line ${i+1} has a name longer than 120 characters.`);if(!Number.isSafeInteger(count)||count<0||count>1000000)throw new Error(`Line ${i+1} needs a whole-number total from 0 to 1,000,000.`);const key=`${name.toLocaleLowerCase()}\u0000${grade}`;const prior=map.get(key);if(prior){if(parts.length===1)prior.count+=1;else throw new Error(`“${name}” appears more than once with an explicit total. Keep only one total line for that student.`);}else{const existing=window.__peacPeople?.records.find(r=>r.week_start===week&&r.grade===grade&&r.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase());map.set(key,{week_start:week,name,grade,count,trash_count:existing?.trash_count||0,note:existing?.note||''});}}return Array.from(map.values());}
 function showRapid(records){rapidRecords=records;$('rapidRows').textContent=records.length.toLocaleString();$('rapidCompliments').textContent=records.reduce((a,r)=>a+r.count,0).toLocaleString();$('rapidGrades').textContent=new Set(records.map(r=>r.grade)).size;$('rapidTable').replaceChildren();for(const r of records.slice(0,100)){const tr=node('tr');tr.append(node('td','',r.name),node('td','',r.grade==='unassigned'?'—':r.grade),node('td','',String(r.count)));$('rapidTable').append(tr);}if(records.length>100){const tr=node('tr'),td=node('td','muted',`…and ${records.length-100} more rows`);td.colSpan=3;tr.append(td);$('rapidTable').append(tr);}$('rapidPreview').classList.remove('hidden');$('saveRapid').classList.remove('hidden');say('rapidStatus',`${records.length} student rows ready. Review the preview, then Save all.`);}
 $('previewRapid').addEventListener('click',()=>{try{showRapid(parseRapid());}catch(e){rapidRecords=[];$('rapidPreview').classList.add('hidden');$('saveRapid').classList.add('hidden');say('rapidStatus',e.message,true);}});$('rapidText').addEventListener('input',()=>{$('saveRapid').classList.add('hidden');$('rapidPreview').classList.add('hidden');rapidRecords=[];say('rapidStatus','');});$('rapidWeek').addEventListener('change',()=>{$('saveRapid').classList.add('hidden');$('rapidPreview').classList.add('hidden');rapidRecords=[];});$('rapidGrade').addEventListener('change',()=>{$('saveRapid').classList.add('hidden');$('rapidPreview').classList.add('hidden');rapidRecords=[];});$('clearRapid').addEventListener('click',()=>{$('rapidText').value='';rapidRecords=[];$('rapidPreview').classList.add('hidden');$('saveRapid').classList.add('hidden');say('rapidStatus','');$('rapidText').focus();});$('saveRapid').addEventListener('click',()=>work('saveRapid','rapidStatus',async()=>{if(!rapidRecords.length)throw new Error('Preview the list again before saving.');const r=await auth.mutate('rapid-people','/api/portal/compliment-people/batch','POST',{records:rapidRecords});await loadPeople();window.PEACWorkspace.refresh?.();say('rapidStatus',`Saved ${r.saved} student rows: ${r.created} new, ${r.updated} updated. ${rapidRecords.reduce((a,x)=>a+x.count,0)} verified compliments are now reflected in the dashboard.`);$('rapidText').value='';rapidRecords=[];$('rapidPreview').classList.add('hidden');$('saveRapid').classList.add('hidden');}));
 let rosterInputs=[];function rosterNames(){const data=window.__peacPeople;if(!data)return[];const grade=$('rosterGrade').value,seen=new Map();for(const r of data.records){if(r.grade!==grade)continue;const k=r.name.trim().toLocaleLowerCase();if(!seen.has(k))seen.set(k,r.name);}return Array.from(seen.values()).sort((a,b)=>a.localeCompare(b));}
 function renderRoster(){const data=window.__peacPeople;if(!data)return;const wrap=$('rosterGrid'),week=$('rosterWeek').value,grade=$('rosterGrade').value,q=$('rosterSearch').value.trim().toLowerCase(),names=rosterNames().filter(n=>n.toLowerCase().includes(q));wrap.replaceChildren();rosterInputs=[];$('rosterEmpty').classList.toggle('hidden',names.length>0);for(const name of names){const current=data.records.find(r=>r.week_start===week&&r.grade===grade&&r.name.toLocaleLowerCase()===name.toLocaleLowerCase());const row=node('label','roster-row'),who=node('span','roster-name',name),input=node('input');input.type='number';input.min='0';input.max='1000000';input.step='1';input.inputMode='numeric';input.value=current?String(current.count):'0';input.dataset.original=input.value;input.dataset.name=name;input.addEventListener('input',updateRosterChanged);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const i=rosterInputs.indexOf(input);rosterInputs[i+1]?.focus();rosterInputs[i+1]?.select();}});row.append(who,input);wrap.append(row);rosterInputs.push(input);}updateRosterChanged();}
 function updateRosterChanged(){let n=0;for(const i of rosterInputs)if(i.value!==i.dataset.original)n++;$('rosterChanged').textContent=String(n);}
 $('rosterWeek').addEventListener('change',renderRoster);$('rosterGrade').addEventListener('change',renderRoster);$('rosterSearch').addEventListener('input',renderRoster);$('saveRoster').addEventListener('click',()=>work('saveRoster','rosterStatus',async()=>{const week=$('rosterWeek').value,grade=$('rosterGrade').value,records=[];for(const input of rosterInputs){const count=Number(input.value);if(!Number.isSafeInteger(count)||count<0||count>1000000)throw new Error(`Check the total for ${input.dataset.name}.`);if(input.value!==input.dataset.original){const existing=window.__peacPeople?.records.find(r=>r.week_start===week&&r.grade===grade&&r.name.toLocaleLowerCase()===input.dataset.name.toLocaleLowerCase());records.push({week_start:week,name:input.dataset.name,grade,count,trash_count:existing?.trash_count||0,note:existing?.note||''});}}if(!records.length){say('rosterStatus','Nothing changed yet. Type this week’s totals first.');return;}const r=await auth.mutate('roster-week','/api/portal/compliment-people/batch','POST',{records});await loadPeople();window.PEACWorkspace.refresh?.();say('rosterStatus',`Saved ${r.saved} changed rows.`);}));$('peopleSearch').addEventListener('input',renderPeople);$('peopleGradeFilter').addEventListener('change',renderPeople);$('reloadPeople').addEventListener('click',()=>work('reloadPeople','peopleStatus',loadPeople));$('openPeopleImport').addEventListener('click',()=>{navigate('reports');$('importDataset').value='people';$('importDataset').dispatchEvent(new Event('change'));$('importPanel').scrollIntoView({block:'start'});});
 async function overview(){const d=await auth.api('/api/portal/summary');$('navLunchCount').textContent=d.lunch_new;$('overviewLunchNotice').textContent=d.lunch_total?`${d.lunch_new} new requests · ${d.lunch_total} total recorded`:'No requests yet. Set up approved contacts to get started.';}
 async function loadLunch(){queue=await auth.api('/api/portal/lunch');const c=queue.counts;$('lunchNew').textContent=c.new;$('lunchContacted').textContent=c.contacted;$('lunchScheduled').textContent=c.scheduled;$('lunchCompleted').textContent=c.completed;$('navLunchCount').textContent=c.new;say('lunchQueueStatus',queue.truncated?'Showing the latest 2,000 requests. Export the private archive for older records.':'');renderRequests();renderOutbox();if(selected){const row=queue.requests.find(r=>r.id===selected.id);if(row)selectRequest(row);else{selected=null;$('lunchDetail').classList.add('hidden');$('lunchEmpty').classList.remove('hidden');}}const m=await auth.api('/api/portal/mail/status');mailEnabled=m.enabled;$('mailMode').textContent=mailEnabled?'SMTP configured':'Draft mode · email sending off';renderOutbox();}
 function renderRequests(){const wrap=$('lunchList');wrap.replaceChildren();if(!queue)return;const q=$('lunchSearch').value.toLowerCase(),f=$('lunchFilter').value;const rows=queue.requests.filter(r=>(f==='all'||r.status===f)&&`${r.reference} ${r.preferred_name} ${r.email}`.toLowerCase().includes(q));if(!rows.length)wrap.append(node('p','empty-hint','No requests match this view. New requests will appear here after the form is enabled.'));for(const r of rows){const b=node('button','request-row'+(selected?.id===r.id?' active':''));b.type='button';const avatar=node('span','request-avatar',r.preferred_name[0]?.toUpperCase()||'L');const info=node('span');info.append(node('strong','',r.preferred_name),node('small','',`${r.reference} · ${r.preferred_date}`));b.append(avatar,info,node('span','state-chip '+r.status,r.status));b.addEventListener('click',()=>selectRequest(r));wrap.append(b);}}
 const supportLabels={company:'Some lunch company',new_people:'Meet new people',finding_group:'Help finding a group'};
 function selectRequest(r){selected=r;renderRequests();$('lunchEmpty').classList.add('hidden');$('lunchDetail').classList.remove('hidden');$('detailReference').textContent=r.reference;$('detailName').textContent=r.preferred_name;const facts=$('requestFacts');facts.replaceChildren();for(const [k,v]of [['School email',r.email],['Grade',r.grade==='unassigned'?'Not specified':r.grade],['Preferred date',r.preferred_date],['Lunch period',r.lunch_period||'Not specified'],['Support',supportLabels[r.support]],['Requested buddy',r.preferred_buddy||'No preference'],['PEAC account match',r.preferred_buddy?(r.matched_buddy_user_id?'Matched approved account':'No unique account match'):'Not requested']])facts.append(node('dt','',k),node('dd','',v));$('detailText').textContent=r.details||'No additional details.';$('requestStatus').value=r.status;$('requestNote').value=r.staff_note;recipientPicker('requestRecipients',queue.contacts);say('requestSaveStatus','');}
 $('lunchSearch').addEventListener('input',renderRequests);$('lunchFilter').addEventListener('change',renderRequests);$('reloadLunch').addEventListener('click',()=>work('reloadLunch','lunchQueueStatus',loadLunch));
 $('requestUpdate').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;work('saveRequest','requestSaveStatus',async()=>{const id=selected.id;await auth.mutate('request:'+id,'/api/portal/lunch/'+id,'PUT',{status:$('requestStatus').value,staff_note:$('requestNote').value,version:selected.version});await loadLunch();say('requestSaveStatus','Next step saved.');});});
 $('routeRequest').addEventListener('click',()=>{if(!selected)return;work('routeRequest','requestSaveStatus',async()=>{await auth.mutate('route:'+selected.id,`/api/portal/lunch/${selected.id}/route`,'POST',{contact_ids:selectedContacts('requestRecipients')});await loadLunch();say('requestSaveStatus','Notifications queued. No email was sent. See the outbox below.');});});
 function renderOutbox(){const wrap=$('outboxList');wrap.replaceChildren();if(!queue)return;if(!queue.outbox.length)wrap.append(node('p','muted','Notifications will appear when a request has approved recipients.'));for(const j of queue.outbox){const row=node('div','outbox-row'),info=node('div');info.append(node('strong','',`${j.reference} → ${j.label}`),node('small','',j.recipient));row.append(info,node('span','state-chip '+j.status,j.status));const actions=node('div','actions');const draft=node('a','btn light','Email draft');draft.href=`/api/portal/mail/${j.id}/draft.eml`;draft.download='peac-notification-draft.eml';actions.append(draft);const preview=node('button','btn light','Preview');preview.type='button';preview.addEventListener('click',()=>previewMail(j));actions.append(preview);if(auth.state.user.role==='admin'&&mailEnabled&&j.status==='queued'){const send=node('button','btn primary','Send');send.type='button';send.addEventListener('click',()=>previewMail(j,true));actions.append(send);}if(auth.state.user.role==='admin'&&['uncertain','sending'].includes(j.status)){const resolve=node('button','btn light','Reconcile');resolve.type='button';resolve.addEventListener('click',()=>reconcile(j));actions.append(resolve);}row.append(actions);wrap.append(row);}}
 const dialog=node('dialog','mail-dialog');dialog.id='mailDialog';dialog.setAttribute('aria-labelledby','mailDialogTitle');const title=node('h3','','Notification preview');title.id='mailDialogTitle';const to=node('p','muted'),body=node('pre','mail-body'),dialogStatus=node('p','inline-status');dialogStatus.id='mailDialogStatus';const dialogActions=node('div','actions'),sendButton=node('button','btn primary','Confirm send'),close=node('button','btn light','Close');sendButton.type=close.type='button';sendButton.id='confirmMailSend';dialogActions.append(sendButton,close);dialog.append(title,to,body,dialogStatus,dialogActions);document.body.append(dialog);close.addEventListener('click',()=>dialog.close());let activeMail=null;
 async function previewMail(j,send=false){try{const p=await auth.api(`/api/portal/mail/${j.id}/preview`);activeMail=j;to.textContent=`To: ${p.to}`;body.textContent=`Subject: ${p.subject}\n\n${p.body}`;sendButton.classList.toggle('hidden',!(auth.state.user.role==='admin'&&mailEnabled&&p.status==='queued'));dialogStatus.textContent=send?'This sends a real notification to the displayed approved inbox.':'Draft preview. Opening or downloading this does not send email.';dialog.showModal();}catch(e){say('mailStatus',e.message,true);}}
 sendButton.addEventListener('click',()=>work('confirmMailSend','mailDialogStatus',async()=>{const r=await auth.api(`/api/portal/mail/${activeMail.id}/send`,'POST',{confirm:'SEND NOTIFICATION'});dialogStatus.textContent=r.message;sendButton.classList.add('hidden');await loadLunch();}));
 async function reconcile(j){const value=prompt('Check your SMTP provider logs FIRST. Type CONFIRMED SENT, CONFIRMED NOT SENT, or CANCEL NOTIFICATION. No automatic retry will happen.');if(!value)return;try{await auth.api(`/api/portal/mail/${j.id}/resolve`,'POST',{confirm:value});await loadLunch();say('mailStatus','Reconciliation saved. A queued notification still needs an explicit send.');}catch(e){say('mailStatus',e.message,true);}}
 async function loadWebsite(){[config,queue]=await Promise.all([auth.api('/api/portal/content'),auth.api('/api/portal/lunch')]);$('schoolLabel').value=config.school_label;$('aboutEditor').value=config.about;$('lunchIntroEditor').value=config.lunch_intro;$('privacyEditor').value=config.privacy_notice;$('lunchEnabled').checked=config.lunch_enabled;recipientPicker('defaultRecipients',queue.contacts,config.default_contact_ids);renderContacts();}
 function renderContacts(){const wrap=$('contactList');wrap.replaceChildren();for(const c of queue.contacts){const row=node('div','contact-row'),info=node('div');info.append(node('strong','',c.label+(c.active?'':' (inactive)')),node('small','',c.email));row.append(info);const edit=node('button','','Edit');edit.type='button';edit.addEventListener('click',()=>{editingContact=c;$('contactLabel').value=c.label;$('contactEmail').value=c.email;$('saveContact').textContent='Save contact changes';$('contactLabel').focus();say('contactStatus','Editing this saved contact.');});const toggle=node('button','',c.active?'Disable':'Enable');toggle.type='button';toggle.addEventListener('click',async()=>{if(c.active&&!confirm('Disable this approved recipient? Removing the last default recipient pauses public requests.'))return;try{await auth.mutate('toggle-contact:'+c.id,'/api/portal/contacts/'+c.id,'PUT',{label:c.label,email:c.email,active:!c.active});await loadWebsite();say('contactStatus','Contact updated.');}catch(e){say('contactStatus',e.message,true);}});row.append(edit,toggle);wrap.append(row);}}
 $('contactForm').addEventListener('submit',e=>{e.preventDefault();work('saveContact','contactStatus',async()=>{const path='/api/portal/contacts'+(editingContact?'/'+editingContact.id:'');await auth.mutate('contact',path,editingContact?'PUT':'POST',{label:$('contactLabel').value,email:$('contactEmail').value,active:editingContact?!!editingContact.active:true});editingContact=null;$('contactForm').reset();$('saveContact').textContent='Add contact';const contacts=await auth.api('/api/portal/contacts');queue.contacts=contacts;const keep=selectedContacts('defaultRecipients');recipientPicker('defaultRecipients',contacts,keep);renderContacts();say('contactStatus','Contact saved. Select default recipients and save the site settings.');});});
 $('websiteForm').addEventListener('submit',e=>{e.preventDefault();work('saveWebsite','websiteStatus',async()=>{await auth.mutate('website','/api/portal/content','PUT',{school_label:$('schoolLabel').value,about:$('aboutEditor').value,lunch_intro:$('lunchIntroEditor').value,privacy_notice:$('privacyEditor').value,lunch_enabled:$('lunchEnabled').checked,default_contact_ids:selectedContacts('defaultRecipients')});say('websiteStatus','Public content saved. Requests are '+($('lunchEnabled').checked?'open.':'paused.'));});});
 function message(role,text){const n=node('div','chat-message '+role);n.append(node('small','',role==='user'?'You':'PEAC Assistant · grounded answer'),node('div','',text));$('chatLog').querySelector('.chat-welcome')?.remove();$('chatLog').append(n);$('chatLog').scrollTop=$('chatLog').scrollHeight;return n;}
 async function ask(question){if(!question.trim())return;message('user',question);const prior=assistantHistory.slice(-8);const data=await auth.api('/api/portal/assistant/ask','POST',{question,history:prior});assistantHistory.push({role:'user',content:question});assistantHistory.push({role:'assistant',content:data.answer});assistantHistory=assistantHistory.slice(-8);const n=message('assistant',data.answer);const meta=node('div','smart-answer-meta');meta.append(node('span','','Private PEAC data'),node('span','',data.intent?.replaceAll('_',' ')||'grounded answer'),node('span','',data.period||'current records'));if(data.context_used)meta.append(node('span','','Follow-up context used'));const refs=node('div','chat-sources');for(const s of data.sources){const a=node('a','',s.label);a.href=s.href;const hash=s.href.split('#')[1];if(hash)a.addEventListener('click',e=>{e.preventDefault();navigate(hash);});refs.append(a);}n.append(meta,refs);if(Array.isArray(data.suggestions)&&data.suggestions.length){const suggestions=node('div','chat-suggestions');for(const q of data.suggestions.slice(0,3)){const b=node('button','',q);b.type='button';b.addEventListener('click',()=>{$('chatQuestion').value=q;$('chatForm').requestSubmit();});suggestions.append(b);}n.append(suggestions);}const feedback=node('div','chat-feedback');for(const [label,rating]of [['Helpful','helpful'],['Needs work','needs_work']]){const b=node('button','',label);b.type='button';b.addEventListener('click',async()=>{try{if(rating==='needs_work'){if(feedback.querySelector('textarea'))return;const input=node('textarea');input.maxLength=600;input.placeholder='Optional correction for admin review. No student details.';input.setAttribute('aria-label','Feedback suggestion');const save=node('button','','Submit feedback');save.type='button';save.addEventListener('click',async()=>{try{await auth.api('/api/portal/assistant/feedback','POST',{turn_id:data.id,rating,suggestion:input.value});feedback.replaceChildren(node('span','','Saved for review. Knowledge was not changed automatically.'));}catch(e){say('chatStatus',e.message,true);}});feedback.append(input,save);input.focus();}else{await auth.api('/api/portal/assistant/feedback','POST',{turn_id:data.id,rating});feedback.replaceChildren(node('span','','Thank you. Feedback saved.'));}}catch(e){say('chatStatus',e.message,true);}});feedback.append(b);}n.append(feedback);$('chatLog').scrollTop=$('chatLog').scrollHeight;}
 $('chatForm').addEventListener('submit',e=>{e.preventDefault();const question=$('chatQuestion').value;work('askAssistant','chatStatus',async()=>{say('chatStatus','Checking saved records...');await ask(question);$('chatQuestion').value='';say('chatStatus','Answer grounded in the current saved records.');});});
 document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{$('chatQuestion').value=b.dataset.question;$('chatForm').requestSubmit();}));$('clearChat').addEventListener('click',()=>{assistantHistory=[];$('chatLog').replaceChildren(node('p','muted','Conversation cleared from this browser tab. Ask another question.'));say('chatStatus','');});
 async function loadKnowledge(){const items=await auth.api('/api/portal/knowledge');const wrap=$('knowledgeList');wrap.replaceChildren();for(const k of items){const row=node('div','knowledge-item');row.append(node('strong','',k.question),node('p','',k.approved?'Approved for retrieval':'Draft, not used by the assistant'));const remove=node('button','text-btn','Remove');remove.type='button';remove.addEventListener('click',async()=>{if(!confirm('Remove this FAQ from the assistant knowledge base?'))return;try{await auth.mutate('knowledge:'+k.id,'/api/portal/knowledge/'+k.id,'DELETE',{});await loadKnowledge();}catch(e){say('faqStatus',e.message,true);}});row.append(remove);wrap.append(row);}}
 $('knowledgeForm').addEventListener('submit',e=>{e.preventDefault();work('saveFAQ','faqStatus',async()=>{await auth.mutate('faq','/api/portal/knowledge','POST',{question:$('faqQuestion').value,answer:$('faqAnswer').value,approved:$('faqApproved').checked});$('knowledgeForm').reset();await loadKnowledge();await loadAssistantFaqs();say('faqStatus','FAQ saved. Only approved answers are used.');});});
 async function loadUsage(){const data=await auth.api('/api/portal/assistant/usage');$('usageStats').replaceChildren(...data.intents.map(x=>node('span','',`${x.intent.replaceAll('_',' ')} · ${x.uses}`)));$('feedbackList').replaceChildren(...data.feedback.map(x=>{const d=node('div','feedback-item');d.append(node('strong','',x.rating==='helpful'?'Helpful':'Needs review'),node('p','',x.suggestion||'No written suggestion.'));return d;}));if(!data.feedback.length)$('feedbackList').append(node('p','muted','Feedback appears here after someone rates an answer. No questions or hidden training are stored.'));}
 $('reloadFeedback').addEventListener('click',()=>work('reloadFeedback','faqStatus',loadUsage));
 async function loadNotifications(){const data=await auth.api('/api/portal/notifications');$('homeNotificationCount').textContent=`${data.unread} unread`;$('navNotificationCount').textContent=String(data.unread);const wrap=$('homeNotificationList');wrap.replaceChildren();if(!data.items.length){wrap.append(node('p','muted','No notifications yet.'));return;}for(const item of data.items){const row=node('div','notification-row'+(item.read_at?'':' unread')),dot=node('span','notification-dot'),body=node('div');body.append(node('strong','',item.title),node('p','',item.body));const side=node('div');side.append(node('small','',new Date(item.created_at).toLocaleString()));if(item.href){const a=node('a','','Open');a.href=item.href;const hash=item.href.split('#')[1];if(hash)a.addEventListener('click',e=>{e.preventDefault();navigate(hash);});side.append(a);}row.append(dot,body,side);wrap.append(row);}}
 async function loadPeacAdminHome(){
   const [dash,summary,lunch]=await Promise.all([auth.api('/api/dashboard'),auth.api('/api/portal/summary'),auth.api('/api/portal/lunch')]);
   $('adminVerifiedTotal').textContent=Number(dash.compliments?.all_time_total||0).toLocaleString();
   $('adminDataDetail').textContent=`${Number(dash.compliments?.days_recorded||0).toLocaleString()} recorded dates · ${Number(dash.compliments?.completed_weeks||0).toLocaleString()} completed weeks`;
   $('adminLunchTotal').textContent=Number(summary.lunch_total||0).toLocaleString();
   $('adminNewRequests').textContent=Number(summary.lunch_new||0).toLocaleString();
   $('adminLunchDetail').textContent=`${Number(lunch.counts?.contacted||0).toLocaleString()} contacted · ${Number(lunch.counts?.scheduled||0).toLocaleString()} scheduled · ${Number(lunch.counts?.completed||0).toLocaleString()} completed`;
   const wrap=$('adminRequestList');wrap.replaceChildren();
   const fresh=(lunch.requests||[]).filter(x=>x.status==='new').slice(0,6);
   if(!fresh.length){wrap.append(node('p','muted','No new Lunch Buddy requests right now.'));return;}
   for(const req of fresh){
     const b=node('button','admin-request-row');b.type='button';
     const info=node('span');info.append(node('strong','',req.preferred_name),node('small','',`${req.reference} · ${req.preferred_date}`));
     b.append(info,node('span','state-chip new','new'));
     b.addEventListener('click',async()=>{navigate('lunch');await loadLunch();const found=queue?.requests.find(x=>x.id===req.id);if(found)selectRequest(found);});
     wrap.append(b);
   }
 }
 async function loadHome(){
   const u=auth.state.user,isPeacAdmin=u?.username?.toLowerCase()==='peacadmin';
   $('roleHomeEyebrow').textContent=isPeacAdmin?'PEACADMIN dashboard':'PEAC account';
   $('roleHomeTitle').textContent=isPeacAdmin?'PEAC control center.':`Welcome, ${u?.display_name||'PEAC member'}.`;
   $('roleHomeCopy').textContent=isPeacAdmin?'Your data, Lunch Buddies, and newest requests in one focused view.':'Jobs and more PEAC features are coming soon.';
   $('roleHomePill').textContent=isPeacAdmin?'PEACADMIN':'Member';
   if(isPeacAdmin){await Promise.all([loadNotifications(),loadPeacAdminHome()]);}
 }
 $('markNotificationsRead')?.addEventListener('click',async()=>{try{await auth.api('/api/portal/notifications/read','POST',{});await loadNotifications();}catch(e){say('dataStatus',e.message,true);}});
 async function loadAssistantFaqs(){const items=await auth.api('/api/portal/assistant/faqs');const select=$('faqPicker');select.replaceChildren();const first=node('option','','Choose a saved FAQ...');first.value='';select.append(first);for(const item of items){const o=node('option','',item.question);o.value=item.question;select.append(o);}$('askFaqBtn').disabled=!select.value;}
 $('faqPicker')?.addEventListener('change',()=>{$('askFaqBtn').disabled=!$('faqPicker').value;});
 $('askFaqBtn')?.addEventListener('click',()=>{const q=$('faqPicker').value;if(!q)return;$('chatQuestion').value=q;$('chatForm').requestSubmit();});
 async function loadQuote(){try{const c=await auth.api('/api/public/config');if(c.quote){$('consoleDailyQuote').textContent=c.quote.text;$('consoleQuoteDate').textContent=c.quote.date;}}catch(_){$('consoleDailyQuote').textContent='Small acts build stronger communities.';$('consoleQuoteDate').textContent='';}}
 function approvalRow(u,home=false){const row=node('div',home?'approval-row':'contact-row'),info=node('div');info.append(node('strong','',u.display_name),node('small','',`${u.username} · ${u.email}`));const actions=node('div',home?'approval-actions':'actions'),approve=node('button',home?'approve':'','Approve'),reject=node('button',home?'reject':'','Reject');approve.type=reject.type='button';approve.addEventListener('click',async()=>{approve.disabled=reject.disabled=true;try{await auth.api('/api/portal/signup-requests/'+u.id+'/approve','POST',{});await loadUsers();}catch(e){say('userStatus',e.message,true);approve.disabled=reject.disabled=false;}});reject.addEventListener('click',async()=>{if(!confirm('Reject this sign-up request?'))return;approve.disabled=reject.disabled=true;try{await auth.api('/api/portal/signup-requests/'+u.id+'/reject','POST',{});await loadUsers();}catch(e){say('userStatus',e.message,true);approve.disabled=reject.disabled=false;}});actions.append(approve,reject);row.append(info,actions);return row;}
 async function loadSignupRequests(){const rows=await auth.api('/api/portal/signup-requests');const settings=$('signupRequestList'),home=$('adminHomeSignupList');settings?.replaceChildren();home?.replaceChildren();if($('homePendingCount'))$('homePendingCount').textContent=`${rows.length} pending`;if($('navSignupCount'))$('navSignupCount').textContent=String(rows.length);if(!rows.length){settings?.append(node('p','muted','No pending sign-up requests.'));home?.append(node('p','muted','No one is waiting for approval.'));return;}for(const u of rows){settings?.append(approvalRow(u,false));home?.append(approvalRow(u,true));}}
 async function loadUsers(){const rows=await auth.api('/api/portal/users');$('userList').replaceChildren();for(const u of rows){const r=node('div','contact-row'),info=node('div');const detail=[u.username,u.email||'no email saved',u.role,u.active?'active':'disabled'].join(' · ');info.append(node('strong','',u.display_name),node('small','',detail));r.append(info);if(u.active&&u.id!==auth.state.user.id){const b=node('button','','Disable');b.type='button';b.addEventListener('click',async()=>{if(!confirm('Disable this account and revoke its signed-in sessions?'))return;try{await auth.api('/api/portal/users/'+u.id,'DELETE',{});await loadUsers();}catch(e){say('userStatus',e.message,true);}});r.append(b);}$('userList').append(r);}await loadSignupRequests();}
 $('userForm').addEventListener('submit',e=>{e.preventDefault();work('createUser','userStatus',async()=>{await auth.api('/api/portal/users','POST',{username:$('newUsername').value,display_name:$('newDisplayName').value,email:$('newUserEmail').value,password:$('newUserPassword').value,role:$('newRole').value});$('userForm').reset();await loadUsers();say('userStatus','Account created. Share its password privately and ask the person to change it.');});});
 $('passwordForm').addEventListener('submit',e=>{e.preventDefault();work('changePassword','passwordStatus',async()=>{await auth.api('/api/portal/password','POST',{current_password:$('oldPassword').value,new_password:$('newPassword').value});$('passwordForm').reset();location.replace('/login');});});
 async function loadSiteFeedback(){if(auth.state.user?.role!=='admin')return;try{const rows=await auth.api('/api/portal/site-feedback');const wrap=$('siteFeedbackList');wrap.replaceChildren();if(!rows.length){wrap.append(node('p','muted','No website feedback yet.'));return;}for(const x of rows){const item=node('div','feedback-item');item.append(node('small','',x.source+' · '+x.created_at),node('p','',x.message));wrap.append(item);}}catch(e){say('privateFeedbackStatus',e.message,true);}}
 $('privateFeedbackBtn')?.addEventListener('click',()=>work('privateFeedbackBtn','privateFeedbackStatus',async()=>{const message=$('privateFeedbackText').value.trim();if(!message)throw Error('Write feedback first.');await auth.api('/api/portal/site-feedback','POST',{message});$('privateFeedbackText').value='';say('privateFeedbackStatus','Feedback saved privately.');await loadSiteFeedback();}));
 $('reloadSiteFeedback')?.addEventListener('click',()=>loadSiteFeedback());
 $('consoleMotion').addEventListener('change',()=>document.documentElement.dataset.motion=$('consoleMotion').checked?'off':'on');
 $('exportCommunity').addEventListener('click',()=>work('exportCommunity','exportStatus',async()=>{const data=await auth.api('/api/portal/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='peac-private-community-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);say('exportStatus','Private export created. Store it securely; it includes Lunch Buddies contact details.');}));
 $('previewPurge').addEventListener('click',()=>work('previewPurge','purgeStatus',async()=>{const r=await auth.api('/api/portal/purge','POST',{days:Number($('retentionDays').value)});say('purgeStatus',`${r.eligible} closed requests before ${r.before} are eligible. No data has been deleted.`);$('confirmPurge').classList.toggle('hidden',!r.eligible);}));
 $('confirmPurge').addEventListener('click',()=>work('confirmPurge','purgeStatus',async()=>{if(!confirm('Permanently remove eligible closed Lunch Buddies requests and their outbox records? Backups are not erased.'))return;const r=await auth.api('/api/portal/purge','POST',{days:Number($('retentionDays').value),confirm:'PURGE CLOSED REQUESTS'});say('purgeStatus',`${r.deleted} requests removed. Existing backups were not changed.`);$('confirmPurge').classList.add('hidden');}));
 auth.ready.then(s=>{document.body.dataset.role=s.user.role;document.body.dataset.username=(s.user.username||'').toLowerCase();$('signedInName').textContent=s.user.display_name;$('signedInRole').textContent=s.user.role;$('userInitial').textContent=s.user.display_name[0].toUpperCase();loadQuote();overview().catch(()=>{});navigate(location.hash.slice(1)||'home');loadSiteFeedback();}).catch(e=>say('dataStatus',e.message,true));
})();
